### ISSUE TITLE
ModuleNotFoundError: No module named 'pretty_print'

### ISSUE THREAD

**Issue by pvieira84** [agusalex/ghostfolio-sync#26]
After merging #25, I'm having the following error: 

<img width="173" alt="Image" src="https://github.com/user-attachments/assets/da15bc0f-a8c2-4f1d-ad5d-625ce814b2ee" />

**Comment by agusalex** [comment]
Thanks for letting me know it's missing that dependency. I'll add that in.

**Comment by agusalex** [comment]
It should be resolved with new image, let me know if that is the case

**Comment by christophkreutzer** [comment]
Hey, thanks for the fast response!

I'm having the same issue. The image on DockerHub is still from seven days ago, did the push fail maybe?

**Comment by agusalex** [comment]
Sorry my bad, now image is updated

**Comment by pvieira84** [comment]
Hey @agusalex, it still fails for me. Maybe you're missing `COPY pretty_print.py .` in the docker file?

**Comment by agusalex** [comment]
You are corrrect, sorry this was another user's contribution and I did not realize this was not an imported package but a script. Just tested this, its now fixed.

**Comment by agusalex** [comment]
If you have any other issues feel free to let me know
